project:
  type: website
  output-dir: docs

website:
  title: "Chris J. Nicolini"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: portfolio.qmd
        text: Portfolio 
      - href: teaching.qmd
        text: Teaching
      - href: resume.qmd
        text: Resume
    right:
      - icon: github
        href: https://github.com/sicn1c/
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/chjn22
      - icon: instagram
        href: https://instagram.com/chris.nicolini

format:
  html:
    theme: styles.scss
    mainfont: 'Jost'
    toc: true
